### ISSUE TITLE
Subgraph does not have ethPrice

### ISSUE THREAD

**Issue by pnghai** [pancakeswap/pancake-subgraph#40]
https://thegraph.com/explorer/subgraph/pancakeswap/exchange this one has ethPrice for Bundle API, yet the source here does not contained related code. Is there anything wrong? @ChefKai

**Comment by ChefKai** [comment]
The subgraph currently deployed at TheGraph is from the codebase - https://github.com/pancakeswap/pancake-v2-subgraph

We are waiting to have a stable BSC network/nodes in order to deploy and sync it over there; in order to avoid having to restart it every 2/3 days, ...; if you check the logs from all the sugraphs within the PancakeSwap organisation hosted at TheGraph, they have many timeout issues, an  are over 48 hours behind at current (even [pancakeswap/pairs](https://thegraph.com/explorer/subgraph/pancakeswap/pairs)); also some of them have crashed due to the BSC nodes used for `eth_getLogs` queries not being able to handle the traffic from all the subgraphs hosted there for the `bsc` network.

- https://status.thegraph.com/incidents/lp0c97hbyfvn
- https://status.thegraph.com/incidents/zm3mfjy6lpnx
