### ISSUE TITLE
SmartChef subgraph not found

### ISSUE THREAD

**Issue by MrPeanutz** [pancakeswap/pancake-subgraph#73]
Link to SmartChef subgraph (https://thegraph.com/explorer/subgraph/pancakeswap/smartchef) doesn't work.

Also, couldn't find it searching on thegraph's website.

**Comment by ChefKai** [comment]
Hello, with the current Binance Smart Chain nodes provided to TheGraph, we cannot index any data below block #7796111, and as `SmartChef` subgraph needs to index starting from block #7151302; it is currently inaccessible. This issue is out of our scope of action, and we can only wait for it to be resolved. Thanks for your patience.

**Comment by ChefKai** [comment]
This subgraph has been deployed at [pancakeswap/smartchef](https://thegraph.com/legacy-explorer/subgraph/pancakeswap/smartchef)
